Update doc according to the changes introduced in ACP2E-2114
AdobeDocs/commerce-php pull request #177
Opened 2023-08-02 08:58 UTC by glanujnehra

## Purpose of this pull request

Payload containing SKU with leading or trailing spaces are now validated and will return an error message in case of failure.

## Affected pages

/pages/development/backward-incompatible-changes/highlights.md

## Links to Magento Open Source code

[http://magento-l3/inventory#187](https://github.com/magento-l3/inventory/pull/187)

2023-08-02 13:50 UTC, jeff-matthews requested changes
Thanks for the PR @glanujnehra!

Just a minor editorial suggestion and fix for linting error.

2023-08-02 13:50 UTC, jeff-matthews commented on src/pages/development/backward-incompatible-changes/highlights.md
> +Payload containing SKU will now be validated for leading or trailing spaces in `rest/V1/inventory/source-items` API.
```suggestion

Payload containing SKU will now be validated for leading and trailing spaces in the `rest/V1/inventory/source-items` API.
```

2023-08-03 06:34 UTC, glanujnehra commented on src/pages/development/backward-incompatible-changes/highlights.md
> +Payload containing SKU will now be validated for leading or trailing spaces in `rest/V1/inventory/source-items` API.
comment addressed

2023-08-03 12:28 UTC, jeff-matthews approved these changes

2023-08-07 14:55 UTC, merged