Update BIC highlights with note about otp_window
AdobeDocs/commerce-php pull request #257
Opened 2024-04-10 19:03 UTC by nathanjosiah

## Purpose of this pull request

This pull request (PR) ...

## Affected pages

- ...

## Links to Magento Open Source code

- ...

2024-04-10 19:30 UTC, meker12 commented on src/pages/development/backward-incompatible-changes/highlights.md
> +The `spomky-labs/otphp` library was updated which introduced a new validation requirement for supplying custom `otp_window` values. This configuration setting controls the grace period (in number of
```suggestion
The `spomky-labs/otphp` library was updated which introduced a new validation requirement for supplying custom `otp_window` values. This configuration setting controls the grace period (in number of seconds) that is allowed for an expired one-time-password (OTP) to be used before it is denied. Previously, the library allowed any number of seconds to be specified, but now the value cannot be longer than the lifetime of a single OTP (usually 30 seconds).  This new requirement means that the configuration value must be changed if it is set longer.
```

2024-04-10 19:30 UTC, meker12 commented on src/pages/development/backward-incompatible-changes/highlights.md
> +If you are affected by this change, admin users may be unable to login and see the message `There was an internal error trying to verify your code`. You can confirm this by checking the `system.log`
```suggestion
If your Commerce application is affected by this change, admin users might see the following message when they log in.  `There was an internal error trying to verify your code`. You can confirm the cause of the error by checking the `system.log` file in `var/log` for an entry `main.ERROR: The leeway must be lower than the TOTP period`.
```

2024-04-10 19:30 UTC, meker12 commented on src/pages/development/backward-incompatible-changes/highlights.md
> +To fix this issue, you must change the value of the configuration path `twofactorauth/google/otp_window` to be shorter than the TOTP period which is usually 30 seconds. For example, you can reset it
```suggestion
To fix this issue, change the value of the configuration path `twofactorauth/google/otp_window` to be shorter than the TOTP period which is usually 30 seconds. For example, you can reset it to the default value of `1` with the command `bin/magento twofactorauth/google/otp_window 1`. You might need to flush the cache to apply the updated configuration. 
```

2024-04-10 20:14 UTC, meker12 commented on src/pages/development/backward-incompatible-changes/highlights.md
> +The `spomky-labs/otphp` library was updated which introduced a new validation requirement for supplying custom `otp_window` values. This configuration setting controls the grace period (in number of
```suggestion
The `spomky-labs/otphp` library was updated which introduced a new validation requirement for supplying custom `otp_window` values. This configuration setting controls the grace period (in number of seconds) that is allowed for an expired one-time-password (OTP) to be used before it is denied. Previously, the library allowed any number of seconds to be specified. Now, the value cannot be higher than the lifetime of a single OTP (usually 30 seconds). This change means that the configuration value must be changed if it is set to 30 or higher.
```

2024-04-10 21:02 UTC, meker12 commented on src/pages/development/backward-incompatible-changes/highlights.md
> +To fix this issue, change the value of the configuration path `twofactorauth/google/otp_window` to be shorter than the TOTP period which is usually 30 seconds. For example, you can reset it to the de
```suggestion
If your Commerce application is affected by this change, admin users might see the following message when they log in: `There was an internal error trying to verify your code`. You can confirm the cause of the error by checking the `system.log` file in `var/log` for an entry `main.ERROR: The leeway must be lower than the TOTP period`.

To fix this issue, change the value of the configuration path `twofactorauth/google/otp_window` to be shorter than the TOTP period which is usually 30 seconds. For example, you can reset it to the default value of `1` with the command `bin/magento twofactorauth/google/otp_window 1`. You might need to flush the cache to apply the updated configuration.
```

2024-04-11 17:38 UTC, meker12 requested changes

2024-04-11 17:38 UTC, meker12 commented on src/pages/development/backward-incompatible-changes/highlights.md
> +
```suggestion
The `spomky-labs/otphp` library was updated which introduced a new validation requirement for supplying custom `otp_window` values. Previously, the library allowed any number to be specified. Now, the value cannot be higher than the lifetime of a single OTP (usually 30 seconds).

If your Commerce application is affected by this change, admin users might see the following message when they log in: `There was an internal error trying to verify your code`. You can confirm the cause of the error by checking the `system.log` file in `var/log` for an entry `main.ERROR: The leeway must be lower than the TOTP period`.

To fix this issue, change the value of the configuration path `twofactorauth/google/otp_window`.   For example, you can reset it to the system default value of `1` with the command `bin/magento twofactorauth/google/otp_window 1`.  A value of `1` indicates that the current OTP code plus one code in the past and one code in the future remain valid at any given point in time.  Changing the value to `2` allows the OTP codes to remain valid for longer during automated testing.  You might need to flush the cache to apply the updated configuration.
```

2024-04-11 19:27 UTC, meker12 commented on src/pages/development/backward-incompatible-changes/highlights.md
> +To fix this issue, change the value of the configuration path `twofactorauth/google/otp_window` to be shorter than the TOTP period which is usually 30 seconds. For example, you can reset it to the de
```suggestion
To fix this issue, change the value of the configuration path `twofactorauth/google/otp_window` to be shorter than the TOTP period which is usually 30 seconds. For example, you can reset it to the default value of `1` with the command `bin/magento config:set twofactorauth/google/otp_window 1`. You might need to flush the cache to apply the updated configuration.
```

2024-04-11 19:41 UTC, keharper commented on src/pages/development/backward-incompatible-changes/highlights.md
> +The `spomky-labs/otphp` library was updated which introduced a new validation requirement for supplying custom `otp_window` values. This configuration setting controls the grace period (in number of
```suggestion
The updated `spomky-labs/otphp` library introduces a new validation requirement for supplying custom `otp_window` values. This configuration setting controls the grace period (in seconds) that an expired one-time-password (OTP) can be used until it is denied. Previously, the library allowed any number of seconds to be specified. Now, the value cannot be higher than the lifetime of a single OTP (usually 30 seconds). You must update this value if it is currently set to 30 or higher.

```

2024-04-11 19:41 UTC, keharper commented on src/pages/development/backward-incompatible-changes/highlights.md
> +To fix this issue, change the value of the configuration path `twofactorauth/google/otp_window` to be shorter than the TOTP period which is usually 30 seconds. For example, you can reset it to the de
```suggestion
To fix this issue, change the value of the configuration path `twofactorauth/google/otp_window` to be shorter than the TOTP period, which is usually 30 seconds. For example, you can reset it to 29 seconds using the `bin/magento config:set twofactorauth/google/otp_window 29` command. You might need to flush the cache to apply the updated configuration.
```

2024-04-11 20:05 UTC, keharper commented on src/pages/development/backward-incompatible-changes/highlights.md
> +The `spomky-labs/otphp` library was updated which introduced a new validation requirement for supplying custom `otp_window` values. This configuration setting controls the grace period (in number of
```suggestion
The  updated`spomky-labs/otphp` library introduced a new validation requirement for supplying custom `otp_window` values. This configuration setting controls how long (in seconds) the system accepts an administrator's one-time-password (OTP) after it has expired. Previously, the library allowed any number of seconds to be specified. Now, the value cannot be higher than the lifetime of a single OTP (usually 30 seconds). If your configuration value is currently 30 or higher, you must change the value.
```

2024-04-11 20:50 UTC, meker12 approved these changes

2024-04-11 22:08 UTC, nathanjosiah commented
Looks good to me

2024-04-11 22:09 UTC, merged